name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-west-1
  ECR_REGISTRY_URI: 634441478571.dkr.ecr.us-west-1.amazonaws.com/demo-app
  ECS_SERVICE: demo_ecs_svc
  ECS_CLUSTER: demo-ecs-cluster
  ECS_TASK_DEFINITION: temp/demo_ecs_app.json
  CONTAINER_NAME: demo-ecs-app

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: openssl update
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
          node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Build Express app
      run: npm run build
    - name: Push Docker Image to ECR
      run: sudo docker build -t ${{ env.ECR_REGISTRY_URI }}:latest .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Push Docker image to ECR
      run: aws ecr get-login-password --region us-west-1 | sudo docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY_URI }} | sudo docker push ${{ env.ECR_REGISTRY_URI }}:latest

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: $ECR_REGISTRY:latest

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
